version: '3.8'
services:
  func-api:
    image: func-api:local-dev
    ports:
      - '8081:80'
    environment:
      KAFKA_CLIENT_ID": FuncManagerClientId
      KAFKA_GROUP_ID": FuncManagerGroupId
      BOOTSTRAPSERVER": 127.0.0.1:19092
      DB_USER: sa
      DB_PASSWORD: LocalAdmin_123
      DB_SERVER: localhost
      DB_DATABASE: tempdb
      FUNC_TOPICS: Demo-WORKFLOW